apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ikea-cert
  namespace: ikea
spec:
  commonName: jeikeanarvana.fun
  secretName: ikea-cert-secret
  dnsNames:
    - jeikeanarvana.fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  revisionHistoryLimit: 1
