apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikea-deployment
  labels:
    app: ikea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ikea
  template:
    metadata:
      labels:
        app: ikea
    spec:
      imagePullSecrets:
        - name: dockerhubcred
      containers:
        - name: ikea
          image: voxfpd/ikea:1.0.1
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: ikea-postgres-postgresql.ikea.svc.cluster.local
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: secretPass666
            - name: DB_NAME
              value: ikea
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
