apiVersion: v1
kind: Service
metadata:
  name: ikea-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    service: ikea-service

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ikea-ingress-rule
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: letsencrypt
    domains:
      - main: ikea.k8s.raclavsky.cz
  routes:
    - match: Host(`ikea.k8s.raclavsky.cz`)
      kind: Rule
      middlewares:
        - name: redirectscheme
          namespace: traefik
      services:
        - name: ikea-service
          port: 80
          scheme: http

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nesnezeno-web-http-ingress-rule
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ikea.k8s.raclavsky.cz`)
      kind: Rule
      middlewares:
        - name: redirectscheme
          namespace: traefik
      services:
        - name: ikea-service
          port: 80
          scheme: http
